CREATE LOGIN [REICORPNET\Admin-SQL Enterprise Admin] FROM WINDOWS WITH DEFAULT_DATABASE = [master], DEFAULT_LANGUAGE = [us_english];
GO
EXEC sp_addsrvrolemember 'REICORPNET\Admin-SQL Enterprise Admin', 'processadmin';
EXEC sp_addsrvrolemember 'REICORPNET\Admin-SQL Enterprise Admin', 'setupadmin';   
GO

GRANT ADMINISTER BULK OPERATIONS, ALTER ANY CONNECTION, ALTER ANY CREDENTIAL, ALTER ANY EVENT SESSION, ALTER ANY LINKED SERVER, ALTER ANY LOGIN, ALTER ANY SERVER AUDIT, ALTER ANY SERVER ROLE, ALTER SERVER STATE, ALTER TRACE, CONNECT SQL, CREATE ANY DATABASE, VIEW ANY DATABASE, VIEW ANY DEFINITION, VIEW SERVER STATE TO [REICORPNET\Admin-SQL Enterprise Admin] WITH GRANT OPTION;
GO

USE msdb
GO
IF NOT EXISTS(SELECT name FROM sys.database_principals WHERE name = 'REICORPNET\Admin-SQL Enterprise Admin')
BEGIN
CREATE USER [REICORPNET\Admin-SQL Enterprise Admin] FOR LOGIN [REICORPNET\Admin-SQL Enterprise Admin] WITH default_schema = [dbo];
END
GO
ALTER ROLE SQLAgentUserRole ADD MEMBER [REICORPNET\Admin-SQL Enterprise Admin]
GO
GRANT ALTER ON ROLE::[SQLAgentOperatorRole] to [REICORPNET\Admin-SQL Enterprise Admin]
GO